courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'

urlpatterns = [
    url(r'^$' ,views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #Course urls
    url(r'^add/$', views.CourseCreate.as_view(), name='course-add'),

    url(r'^(?P<pk>[0-9]+)/chapter/update/$', views.CourseUpdate.as_view(), name='course-update'),

    url(r'^(?P<pk>[0-9]+)/chapter/delete/$', views.CourseDelete.as_view(), name='course-delete'),

    url(r'^(?P<pk>[0-9]+)/chapter/add/$', views.ChapterCreate.as_view(), name='chapter-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<pk>[0-9]+)/$', views.ChapterView.as_view(), name='chapter-detail'),

    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/text/add$', views.TextBlockCreate.as_view(), name='text-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/video/add$', views.AddVideoBlock.as_view(), name='video-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/images/add$', views.AddImageBlock.as_view(),name='images-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/quiz/add$', views.QuizCreate.as_view(), name='quiz-add'),
]

forum/urls.py
from django.conf.urls import url
from . import views as forum_views

urlpatterns = [
    url(r'^$', forum_views.forum, name='forum'),
    url(r'^(?P<slug>[\w-]+)/$', forum_views.topic, name='topic'),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load i18n %}


<html lang="en">
    <head>
        <title>{% block title %}eMasters{% endblock %}</title>
        <meta charset="utf-8">

        <link href="https://fonts.googleapis.com/css?family=Nunito|PT+Sans" rel="stylesheet">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

        <link rel='shortcut icon' type='image/x-icon' href = "{% static 'img/favicon.png' %}">
    </head>

<body>
    <div id="container">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="http://127.0.0.1:8000"><img src ="{% static 'img/logo.jpg' %}"/></a>
                </div>

                <div class="collapse navbar-collapse" id ="navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'courses:index'%}">
                                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                                Course
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'forum' %}">
                                <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp;
                                Forum
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'courses:course-add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Add Course
                            </a>
                        </li>
                        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'about' %}"><span></span>&nbsp;About</a></li>
                        <li><a href="{% url 'registration-register' %}"><span class="glyphicon glyphicon-user"></span>&nbsp;Register</a></li>
                        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div id="content">
            {% block  contenttitle %}
            {% endblock %}

            {% block content %}
            {% endblock %}
        </div>

        <footer>
            <p>Copyright &copy; 2017 - eMasters</p>
        </footer>
    </div>

    <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
</body>
</html>