courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'

urlpatterns = [
    url(r'^$' ,views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #Course urls
    url(r'^add/$', views.CourseCreate.as_view(), name='course-add'),

    url(r'^(?P<pk>[0-9]+)/chapter/update/$', views.CourseUpdate.as_view(), name='course-update'),

    url(r'^(?P<pk>[0-9]+)/chapter/delete/$', views.CourseDelete.as_view(), name='course-delete'),

    url(r'^(?P<pk>[0-9]+)/chapter/add/$', views.ChapterCreate.as_view(), name='chapter-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<pk>[0-9]+)/$', views.ChapterView.as_view(), name='chapter-detail'),

    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/text/add$', views.TextBlockCreate.as_view(), name='text-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/video/add$', views.AddVideoBlock.as_view(), name='video-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/images/add$', views.AddImageBlock.as_view(),name='images-add'),
    url(r'^(?P<course_pk>[0-9]+)/chapter/(?P<chapter_pk>[0-9]+)/block/quiz/add$', views.QuizCreate.as_view(), name='quiz-add'),
]

forum/urls.py
from django.conf.urls import url
from . import views as forum_views

urlpatterns = [
    url(r'^$', forum_views.forum, name='forum'),
    url(r'^(?P<slug>[\w-]+)/$', forum_views.topic, name='topic'),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Course(models.Model):
    name = models.CharField(max_length=25)
    logo = models.FileField(null=False, blank=False)
    date_created = models.DateTimeField(auto_now_add=True)
    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'pk':self.pk})

    def _str_(self):
        # string repreetnacija objekta
        return self.name


class Chapter(models.Model):
    name = models.CharField(max_length=25)
    date_created = models.DateTimeField(auto_now_add=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def _str_(self):
        # string repreetnacija objekta
        return   self.chapter_name

class Block(models.Model):
    title = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    chapter = models.ForeignKey(Chapter)

class TextBlock(Block):
    text = models.TextField()

class VideoBlock(Block):
    link = models.FileField(null=False, blank=False)

class ImageBlock(Block):
    image = models.FileField()

class QuizBlock(Block):
    question = models.CharField(max_length=255)
    answer = models.CharField(max_length=255)

courses/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import authenticate, login
from django.views import  generic
from django.views.generic import  View
from django.views import generic
from .models import Course, Chapter, Block, TextBlock, VideoBlock, ImageBlock, QuizBlock


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'courses/index.html'
    context_object_name = 'all_courses'

    def get_queryset(self):
        return Course.objects.all()

class DetailView(generic.DetailView):
    model = Course
    template_name = 'courses/detail.html'

#Course
class CourseCreate(CreateView):
    model = Course
    fields = ['name', 'logo']

    def get_success_url(self):
        return reverse_lazy('courses:detail', kwargs={'pk':self.object.id})


class CourseUpdate(UpdateView):
    model = Course
    fields = ['name', 'logo']

    def get_success_url(self):
        return reverse_lazy('courses:detail', kwargs={'pk':self.object.id})

class CourseDelete(DeleteView):
    model = Course
    success_url = reverse_lazy('courses:index')

#Chapter
class ChapterCreate(CreateView):
    model = Chapter
    fields = ['name']

    def form_valid(self,form):
        course = Course.objects.get(id = self.kwargs['pk'])
        form.instance.course=course
        return super(ChapterCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:detail', kwargs={'pk':self.kwargs['pk']})

class ChapterUpdate(UpdateView):
    model = Chapter
    fields = ['name']

class ChapterDelete(DeleteView):
    model = Chapter
    success_url = reverse_lazy('courses:detail')


class ChapterView(generic.DetailView):
    model = Chapter
    template_name = 'courses/chapter_detail.html'

    def get_context_data(self, **kwargs):
        course = Course.objects.get(id=self.kwargs['course_pk'])
        # Call the base implementation first to get a context
        context = super(ChapterView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['chapter_list'] = course.chapter_set.all()
        context['course'] = course
        return context

#Lesson
class BlockCreate(CreateView):
    model = Block
    fields = ['title', 'chapter']

class BlockUpdate(UpdateView):
    model = Block
    fields = ['title', 'chapter']

class BlockDelete(UpdateView):
    model = Block
    success_url = reverse_lazy('courses:detail')


class TextBlockCreate(CreateView):
    model = TextBlock
    fields = ['title', 'text']
    template_name = 'courses/add_text.html'

class TextBlockUpdate(UpdateView):
    model = TextBlock
    fields = ['title', 'text']

class TextBlockDelete(DeleteView):
    model = TextBlock
    fields = ['title', 'text']
    success_url = reverse_lazy('courses:index')

class AddVideoBlock(CreateView):
    model = VideoBlock
    fields = ['link']
    template_name = 'courses/add_video.html'

    def form_valid(self,form):
        chapter = Chapter.objects.get(id = self.kwargs['chapter_pk'])
        form.instance.chapter = chapter
        return super(AddVideoBlock, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:chapter-detail', kwargs={'course_pk':self.kwargs['course_pk'], 'pk':self.kwargs['chapter_pk']})


class UpdateVideoBlock(UpdateView):
    model = VideoBlock
    fields = ['link']
    template_name = 'courses/add_video.html'

    def form_valid(self,form):
        chapter = Chapter.objects.get(id = self.kwargs['chapter_pk'])
        form.instance.chapter = chapter
        return super(AddVideoBlock, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:chapter-detail', kwargs={'course_pk':self.kwargs['course_pk'], 'pk':self.kwargs['chapter_pk']})

class DeleteVideoBlock(DeleteView):
    model = VideoBlock
    fields = ['link']
    success_url = reverse_lazy('courses:detail')

class AddImageBlock(CreateView):
    model = ImageBlock
    fields = ['image']
    template_name = 'courses/add_image.html'

    def form_valid(self,form):
        chapter = Chapter.objects.get(id = self.kwargs['chapter_pk'])
        form.instance.chapter = chapter
        return super(AddImageBlock, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:chapter-detail', kwargs={'course_pk':self.kwargs['course_pk'], 'pk':self.kwargs['chapter_pk']})


class UpdateImageBlock(UpdateView):
    model = ImageBlock
    fields = ['image']
    template_name = 'courses/add_image.html'

    def form_valid(self,form):
        chapter = Chapter.objects.get(id = self.kwargs['chapter_pk'])
        form.instance.chapter = chapter
        return super(AddImageBlock, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:chapter-detail', kwargs={'course_pk':self.kwargs['course_pk'], 'pk':self.kwargs['chapter_pk']})


class DeleteImageBlock(DeleteView):
    model = ImageBlock
    fields = ['image']
    success_url = reverse_lazy('courses:index')





class QuizCreate(CreateView):
    model = QuizBlock
    fields = ['question', 'answer']
    template_name = 'courses/add_quiz.html'

    def form_valid(self,form):
        chapter = Chapter.objects.get(id = self.kwargs['chapter_pk'])
        form.instance.chapter = chapter
        return super(QuizCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:chapter-detail', kwargs={'course_pk':self.kwargs['course_pk'], 'pk':self.kwargs['chapter_pk']})

class QuizUpdate(UpdateView):
    model = QuizBlock
    fields = ['question', 'answer']

class QuizDelete(DeleteView):
    model = QuizBlock
    fields = ['question', 'answer']

templates/courses/add_image.html
{% extends 'base.html '%}
{% block contenttitle %} Add multimedia {% endblock %}
{% block album_active %} active {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <p>Add image </p>
                                <input type="file" name="image">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/courses/add_quiz.html
{% extends 'base.html '%}
{% block title %} Add quiz {% endblock %}
{% block album_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <p>Write your question  </p>
                                <input type="text" name="question" /><br>
                                <p>Write your answer</p>
                                <input type="text" name="answer" /><br>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/courses/add_text.html
{% extends 'base.html '%}
{% block title %} Add context {% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                Enter your text here: <textarea name="comment"></textarea><br>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/courses/add_video.html
{% extends 'base.html '%}
{% block title %} Add multimedia {% endblock %}
{% block album_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <p> Add video: </p>
                                <input type="text" name="link" />
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/courses/chapter_detail.html
{% extends 'base.html' %}
{% block  title %} Chapter Details {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body ">
                    <form class="entry-form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <li class="">
                            <a href="{% url 'courses:text-add' course.pk chapter.pk  %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Add text block
                             </a>
                        </li>

                        <li class="">
                            <a href="{% url 'courses:video-add' course.pk chapter.pk  %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Add video
                             </a>
                        </li>

                        <li class="">
                            <a href="{% url 'courses:images-add' course.pk chapter.pk  %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Add image
                             </a>
                        </li>

                        <li class="">
                            <a href="{% url 'courses:quiz-add' course.pk chapter.pk  %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Add quiz
                             </a>
                        </li>
                        <div class="col-sm-offset-6 col-sm-12">
                            <button type="submit">Submit</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/courses/chapter_form.html
{% extends 'base.html' %}
{% block contenttitle %} <div class="container-header container-header-text"><h2>Add a new chapter</h2></div> {% endblock %}
{% block album_active %} active {% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
    <form class="entry-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'courses/form_template.html'%}
        <button type="submit" class="col-md-offset-5">Submit</button>
    </form>
</div>
{% endblock %}

templates/courses/course_form.html
{% extends 'base.html '%}
{% block contenttitle %} <div class="container-header container-header-text"><h2>- COURSE -</h2></div> {% endblock %}
{% block album_active %} active {% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
    <form class="entry-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'courses/form_template.html'%}
        <div class="col-sm-offset-6 col-sm-12">
            <button type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

templates/courses/detail.html
{% extends 'base.html' %}

{% block contenttitle %}
<div class="container-header container-header-text"><h2>{{ course.name }}</h2></div>
<div class="col-md-3">
<div class="thumbnail-img col-md-4"><img src="{{ course.logo.url }}" class="img-responsive"></div>
</div>
{% endblock %}

{% block content %}
{% if error_message %}
<p><strong>{{ error_message}}</strong>></p>
{% endif %}
<div class="col-md-9">
    {%for chapter in course.chapter_set.all %}
    <div id="chapter{{forloop.counter}}" class="chapter-section">
    <label for = "chapter{{forloop.counter}}">
        <a href=" {% url 'courses:chapter-detail' course_pk=course.pk pk=chapter.pk %}" >{{chapter.name}}</a>
    </label><br>
    </div>
    {% endfor %}
    <li class="add-button col-sm-2">
        <a href="{% url 'courses:chapter-add' pk=course.id  %}">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
            Add Chapter
         </a>
    </li>
</div>
{% endblock %}

templates/courses/form_template.html
{% for field in form %}
<div class="col-sm-offset-2 col-sm-10">
    <span class="text-danger small">{{ field.errors }}</span>
</div>
<label>{{ field.label_tag }}</label>
<div class="col-sm-10 input-field">{{ field }}</div>
{% endfor %}

templates/courses/index.html
{% extends 'base.html' %}


{% block content %}

{% if all_courses %}
<div class="container-header container-header-text"><h3>COURSES</h3></div>
<ul class="course-content">
    {% for course in all_courses %}
    <div class="col-sm-4 col-lg-2">
        <div class="thumbnail">
            <div class="thumbnail-img">
                <a href="{% url 'courses:detail' course.id %}">
                    <img src="{{ course.logo.url }}" class="img-responsive" />
                </a>
            </div>
            <div class="caption">
                <h2>{{ course.name }}</h2>
            <!-- Details -->
                <a href="{% url 'courses:detail' course.id %}" class="btn btn-primary btn-sm">View Details</a>
            <!-- Delete -->
                <form action="{% url 'courses:course-delete' course.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="course_id" value="{{ course.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
            <!-- Update -->
                <form action="{% url 'courses:course-update' course.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="course_id" value="{{ course.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-edit"></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</ul>
{% else %}
<h3>There are no courses</h3>
{% endif %}
{% endblock %}

templates/courses/lesson_add.html
{% extends 'base.html' %}

{% for field in form %}
 <div class="form-group">
     <div class="col-sm-offset-2 col-sm-10">
         <span class="text-danger small">{{ field.errors }}</span>
     </div>
     <label class="control-label col-sm-2">{{ field.label_tag }}</label>
     <div class="col-sm-10">{{ field }}</div>
 </div>
{% endfor %}